// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.0
// Source: dropshipbe.proto

package server

import (
	"context"

	"dropshipbe/dropshipbe"
	"dropshipbe/internal/logic"
	"dropshipbe/internal/svc"
)

type DropshipbeServer struct {
	svcCtx *svc.ServiceContext
	dropshipbe.UnimplementedDropshipbeServer
}

func NewDropshipbeServer(svcCtx *svc.ServiceContext) *DropshipbeServer {
	return &DropshipbeServer{
		svcCtx: svcCtx,
	}
}

// --- Products ---
func (s *DropshipbeServer) GetProducts(ctx context.Context, in *dropshipbe.EmptyRequest) (*dropshipbe.ProductListResponse, error) {
	l := logic.NewGetProductsLogic(ctx, s.svcCtx)
	return l.GetProducts(in)
}

func (s *DropshipbeServer) GetProductBySlug(ctx context.Context, in *dropshipbe.GetProductBySlugRequest) (*dropshipbe.Product, error) {
	l := logic.NewGetProductBySlugLogic(ctx, s.svcCtx)
	return l.GetProductBySlug(in)
}

func (s *DropshipbeServer) GetProductsByCategory(ctx context.Context, in *dropshipbe.GetProductsByCategoryRequest) (*dropshipbe.ProductListResponse, error) {
	l := logic.NewGetProductsByCategoryLogic(ctx, s.svcCtx)
	return l.GetProductsByCategory(in)
}

func (s *DropshipbeServer) GetRelatedProducts(ctx context.Context, in *dropshipbe.GetRelatedProductsRequest) (*dropshipbe.ProductListResponse, error) {
	l := logic.NewGetRelatedProductsLogic(ctx, s.svcCtx)
	return l.GetRelatedProducts(in)
}

func (s *DropshipbeServer) GetFeaturedProducts(ctx context.Context, in *dropshipbe.EmptyRequest) (*dropshipbe.ProductListResponse, error) {
	l := logic.NewGetFeaturedProductsLogic(ctx, s.svcCtx)
	return l.GetFeaturedProducts(in)
}

func (s *DropshipbeServer) GetNewProducts(ctx context.Context, in *dropshipbe.EmptyRequest) (*dropshipbe.ProductListResponse, error) {
	l := logic.NewGetNewProductsLogic(ctx, s.svcCtx)
	return l.GetNewProducts(in)
}

func (s *DropshipbeServer) CreateProduct(ctx context.Context, in *dropshipbe.CreateProductRequest) (*dropshipbe.Product, error) {
	l := logic.NewCreateProductLogic(ctx, s.svcCtx)
	return l.CreateProduct(in)
}

// --- Shop Search ---
func (s *DropshipbeServer) GetShop(ctx context.Context, in *dropshipbe.ShopSearchParams) (*dropshipbe.ProductListResponse, error) {
	l := logic.NewGetShopLogic(ctx, s.svcCtx)
	return l.GetShop(in)
}

// --- Media/Galleries ---
func (s *DropshipbeServer) GetSocialProductVideos(ctx context.Context, in *dropshipbe.GetSocialProductVideoRequest) (*dropshipbe.GalleryListResponse, error) {
	l := logic.NewGetSocialProductVideosLogic(ctx, s.svcCtx)
	return l.GetSocialProductVideos(in)
}

// --- FAQs ---
func (s *DropshipbeServer) GetProductFaqs(ctx context.Context, in *dropshipbe.GetProductFaqsRequest) (*dropshipbe.FaqListResponse, error) {
	l := logic.NewGetProductFaqsLogic(ctx, s.svcCtx)
	return l.GetProductFaqs(in)
}

func (s *DropshipbeServer) CreateProductFaq(ctx context.Context, in *dropshipbe.CreateProductFaqRequest) (*dropshipbe.Faq, error) {
	l := logic.NewCreateProductFaqLogic(ctx, s.svcCtx)
	return l.CreateProductFaq(in)
}

// --- Reviews ---
func (s *DropshipbeServer) GetProductReviews(ctx context.Context, in *dropshipbe.GetProductReviewsRequest) (*dropshipbe.ReviewSummary, error) {
	l := logic.NewGetProductReviewsLogic(ctx, s.svcCtx)
	return l.GetProductReviews(in)
}

func (s *DropshipbeServer) CreateProductReview(ctx context.Context, in *dropshipbe.CreateProductReviewRequest) (*dropshipbe.ReviewItem, error) {
	l := logic.NewCreateProductReviewLogic(ctx, s.svcCtx)
	return l.CreateProductReview(in)
}

// --- UI Items (Sliders, Categories, Banners) ---
func (s *DropshipbeServer) GetSliderItems(ctx context.Context, in *dropshipbe.EmptyRequest) (*dropshipbe.SliderListResponse, error) {
	l := logic.NewGetSliderItemsLogic(ctx, s.svcCtx)
	return l.GetSliderItems(in)
}

func (s *DropshipbeServer) GetCategoryItems(ctx context.Context, in *dropshipbe.EmptyRequest) (*dropshipbe.CategoryListResponse, error) {
	l := logic.NewGetCategoryItemsLogic(ctx, s.svcCtx)
	return l.GetCategoryItems(in)
}

func (s *DropshipbeServer) GetBannerItems(ctx context.Context, in *dropshipbe.EmptyRequest) (*dropshipbe.BannerListResponse, error) {
	l := logic.NewGetBannerItemsLogic(ctx, s.svcCtx)
	return l.GetBannerItems(in)
}

func (s *DropshipbeServer) GetVideoBanner(ctx context.Context, in *dropshipbe.EmptyRequest) (*dropshipbe.Banner, error) {
	l := logic.NewGetVideoBannerLogic(ctx, s.svcCtx)
	return l.GetVideoBanner(in)
}

// --- Blogs ---
func (s *DropshipbeServer) GetBlogItems(ctx context.Context, in *dropshipbe.EmptyRequest) (*dropshipbe.BlogListResponse, error) {
	l := logic.NewGetBlogItemsLogic(ctx, s.svcCtx)
	return l.GetBlogItems(in)
}

func (s *DropshipbeServer) GetBlogBySlug(ctx context.Context, in *dropshipbe.GetBlogBySlugRequest) (*dropshipbe.BlogDetailResponse, error) {
	l := logic.NewGetBlogBySlugLogic(ctx, s.svcCtx)
	return l.GetBlogBySlug(in)
}

func (s *DropshipbeServer) CreateNewBlog(ctx context.Context, in *dropshipbe.CreateNewBlogRequest) (*dropshipbe.Blog, error) {
	l := logic.NewCreateNewBlogLogic(ctx, s.svcCtx)
	return l.CreateNewBlog(in)
}

// --- Options ---
func (s *DropshipbeServer) CreateOption(ctx context.Context, in *dropshipbe.CreateOptionRequest) (*dropshipbe.Option, error) {
	l := logic.NewCreateOptionLogic(ctx, s.svcCtx)
	return l.CreateOption(in)
}

func (s *DropshipbeServer) CreateOptionValue(ctx context.Context, in *dropshipbe.CreateOptionValueRequest) (*dropshipbe.OptionValue, error) {
	l := logic.NewCreateOptionValueLogic(ctx, s.svcCtx)
	return l.CreateOptionValue(in)
}

// --- Authentication ---
func (s *DropshipbeServer) Login(ctx context.Context, in *dropshipbe.LoginRequest) (*dropshipbe.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// --- Files ---
func (s *DropshipbeServer) UploadFile(ctx context.Context, in *dropshipbe.UploadFileRequest) (*dropshipbe.UploadFileResponse, error) {
	l := logic.NewUploadFileLogic(ctx, s.svcCtx)
	return l.UploadFile(in)
}

func (s *DropshipbeServer) DeleteFile(ctx context.Context, in *dropshipbe.DeleteFileRequest) (*dropshipbe.DeleteFileResponse, error) {
	l := logic.NewDeleteFileLogic(ctx, s.svcCtx)
	return l.DeleteFile(in)
}

func (s *DropshipbeServer) Ping(ctx context.Context, in *dropshipbe.Request) (*dropshipbe.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
